"""v0.2.0 IMS Upload fields

Revision ID: ec4e43ee9481
Revises: 
Create Date: 2026-07-25 21:13:06.600039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4e43ee9481'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ims_uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('file_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('total_rows', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processed_rows', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('failed_rows', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('new_representatives', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_representatives', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('new_products', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_products', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ims_uploads_file_hash'), ['file_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ims_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ims_uploads_file_hash'))
        batch_op.drop_column('updated_products')
        batch_op.drop_column('new_products')
        batch_op.drop_column('updated_representatives')
        batch_op.drop_column('new_representatives')
        batch_op.drop_column('failed_rows')
        batch_op.drop_column('processed_rows')
        batch_op.drop_column('total_rows')
        batch_op.drop_column('file_hash')
        batch_op.drop_column('week')

    # ### end Alembic commands ###
