from pathlib import Path

p = Path('app/services/ims_import_service.py')
s = p.read_text(encoding='utf-8')
old_init = '''        self._pending_raw_records = 0\n        self._raw_batch = []\n'''
new_init = '''        self._pending_raw_records = 0\n        self._raw_batch = []\n        self._brick_assignment_cache = {}\n'''
if old_init not in s:
    raise SystemExit('init anchor not found')
s = s.replace(old_init, new_init, 1)
old_func = '''    def _upsert_auto_brick_assignment(self, representative_id, year, month, brick, territory=None, city=None):\n        \"\"\"Add one membership without replacing a manually maintained member row.\"\"\"\n        assignment = RepresentativeBrickAssignment.query.filter_by(\n            representative_id=representative_id, year=year, month=month, brick=brick\n        ).first()\n        if assignment is None:\n            db.session.add(RepresentativeBrickAssignment(\n                representative_id=representative_id, year=year, month=month,\n                quarter=self.quarter_for(month), brick=brick, territory=territory,\n                city=city, source=\"AUTO\",\n            ))\n            return\n        if assignment.source != \"MANUAL\":\n            if territory and not assignment.territory:\n                assignment.territory = territory\n            if city and not assignment.city:\n                assignment.city = city\n'''
new_func = '''    def _upsert_auto_brick_assignment(self, representative_id, year, month, brick, territory=None, city=None):\n        \"\"\"Add one membership without replacing a manually maintained member row.\n\n        A brick can be encountered first from staged RAW rows and again from\n        the multi-TTS workbook pass.  After a replace import the period table\n        can be empty, so a database query alone cannot reliably see a pending\n        unflushed INSERT.  Cache the ORM object by the database unique key so\n        repeated evidence in the same import updates the same row instead of\n        scheduling a duplicate INSERT.\n        \"\"\"\n        key = (int(representative_id), int(year), int(month), str(brick))\n        assignment = self._brick_assignment_cache.get(key)\n        if assignment is None:\n            assignment = RepresentativeBrickAssignment.query.filter_by(\n                representative_id=representative_id, year=year, month=month, brick=brick\n            ).first()\n            if assignment is None:\n                assignment = RepresentativeBrickAssignment(\n                    representative_id=representative_id, year=year, month=month,\n                    quarter=self.quarter_for(month), brick=brick, territory=territory,\n                    city=city, source=\"AUTO\",\n                )\n                db.session.add(assignment)\n            self._brick_assignment_cache[key] = assignment\n        if assignment.source != \"MANUAL\":\n            if territory and not assignment.territory:\n                assignment.territory = territory\n            if city and not assignment.city:\n                assignment.city = city\n'''
if old_func not in s:
    raise SystemExit('assignment anchor not found')
s = s.replace(old_func, new_func, 1)
p.write_text(s, encoding='utf-8')

Path('tests/test_week7_assignment_dedupe_contract.py').write_text('''from pathlib import Path\n\n\ndef test_assignment_upsert_uses_import_local_unique_key_cache():\n    source = Path("app/services/ims_import_service.py").read_text(encoding="utf-8")\n    assert "self._brick_assignment_cache = {}" in source\n    start = source.index("def _upsert_auto_brick_assignment")\n    end = source.index("def sync_brick_assignments", start)\n    block = source[start:end]\n    assert "key = (int(representative_id), int(year), int(month), str(brick))" in block\n    assert "self._brick_assignment_cache.get(key)" in block\n    assert "self._brick_assignment_cache[key] = assignment" in block\n    assert "assignment.source != \\\"MANUAL\\\"" in block\n''', encoding='utf-8')
